apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f code/compose-blocks/compose-working.yml
    kompose.version: 1.2.0 (99f88ef)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka2
  name: kafka2
spec:
  ports:
  - name: "34002"
    port: 34002
    targetPort: 9092
  selector:
    io.kompose.service: kafka2
status:
  loadBalancer: {}
