apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f code/compose-blocks/compose-working.yml
    kompose.version: 1.2.0 (99f88ef)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka1
  name: kafka1
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kafka1
    spec:
      containers:
      - image: benjguin/boontadata-kafka:0.1
        name: ks1
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "34001"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "TODO"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zk1:2181
        - name: KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS
          value: "120000"
        ports:
        - containerPort: 9092
        resources: {}
      restartPolicy: Always
status: {}
