# $BOONTADATA_DOCKER_REGISTRY/boontadata/flinkworker
#
# VERSION   0.1

FROM $BOONTADATA_DOCKER_REGISTRY/boontadata/flinkbase:0.1

MAINTAINER boontadata <contact@boontadata.io>

CMD ["/opt/flink/bin/start-worker.sh"]
